spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projet_eventz
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/

